# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GG_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GG_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  GG_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GG Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GG:
ifneq (,$(GG_config))
	@echo "==== Building GG ($(GG_config)) ===="
	@${MAKE} --no-print-directory -C GG -f Makefile config=$(GG_config)
endif

Sandbox: GG
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C GG -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GG"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"